spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}AYBHabLKOiyzOWjejw1+ln9SDpGCbUfPjEZdB/IPztlfedswJUwq8zSvAAMQKb5Efa6zMFa84y9xzbFvlRKMD52SUUNShXviPFAA4zgomrtWteTi9041nZX1W13OsEeMOkinCgFpj8pKtF34yGEN4SLq+Ew2sACS0gj+aBF7t8VB8bOXA9HO2NOEt/g3XrUgzyrR5t01RscY8zs+5uqVtGrPiSmSTngNkoqI6928ywRtBffh7BBFk9KJrsTrUAohB61NqvO2j0m0FNpu6TtsSnRPImQChPMPAltuFS4mW11ba1sSYAKq1K8MTUEiwdYapclqiWgdzmI6TtfDDPupCZkssoCaMjdGstnmVTr97sdV2E+y4b9AejIDixzYmbcYsHq2BiZAvoCTV07H774NnW0G/1VjNmWg7hK+MvHWmfWaOLk5Zka6R9lSgWXY2OGdQk0w9JFNV9PxYycSCr5pBMIqGb1fcy5f085mKoisUrIg+V9P/ugdGoMRKUO7oElYeuL4I5krr/mTWCC8JRQIpi+lXYootTos0mNqr9ujtiuuBA=='

order-service:
  url: http://order-service/order-service/%s/orders
  exception:
    orders-is-empty: User's orders is empty.
# app:
#   payment:
#     apiToken: '{cipher}AYBiqIwR47EUXVMiUUgQA3MY65xE1hPU53UhatBAH5eoDPTnWnUBggXrGYtBCgy2+wpCZieRQLYA1w+pA6U81RdD/FyEVKwxEoPfuwgQaaFNPBkbxKc1Ag1ot1jpGM+P5uiROQ5bSd40Dh6Yzf+crbZwpe4szLddmJ7fs4NaHCT4OEsRrEpe2wPZwnGyTQQyH05N4O7WVhNFnSqS8IWHnmRjkKTgMW8gFYt1f1pZ8uUaFo71vjQ9zrcwjtIGJuXepq2001XW3/y+oKkXLmoHlbWlUxS9auuRI7QpZIqBjrIqjQ74pdHsyVwIyl6I690UleggooE8WmSs/EFQipsLOLJG8ShLisuKnZcG4xn+cw2OTt8YNCZpH2HojSCVP5RmsFnrvoli3IbdLNme8dD95yg7jQZvGZLyZGtA4HNdqerXCtDSleFcxvzCu3LW1AOv0lhfxMT70qBXlMjX2bHtnmCJ/ZABESX6nXoUB3GFSmWHvmEr0pixEQMOmIb77p6i0t6NOSgz2Qt7RjxnhgMlbUBsp9l83cHeDt4E1BDkHp8VccghjEfAI0jVoSPULOQdOVs='

# logging:
#   level:
#     root: INFO
